version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
build:
  verbosity: minimal
deploy:
- provider: GitHub
  release: d3d8-wrapper v$(appveyor_build_version)
  auth_token:
    secure: SXMI7bm5RKh5j1S8A8dnUP2HFw97xHHlJH+mA0hx819vtxOPCpMFY3aFZ+2v16ri
  artifact: d3d8.zip